tensorlayerx/backend/ops/torch_nn.py
=> Update torch backend

examples/model_zoo/resnet.py, tensorlayerx/nn/layers/deprecated.py
=> Added pooling deprecated

requirements/requirements_paddle.txt, tensorlayerx/nn/core/core_tensorflow.py, tensorlayerx/nn/core/core_torch.py, tensorlayerx/nn/layers/recurrent.py
=> Added TF collection of list parameters 

tensorlayerx/nn/core/core_tensorflow.py
=> Added TF collection of dict parameters and parameters

examples/basic_tutorials/Parameter_Container.py, tensorlayerx/nn/core/core_tensorflow.py, tensorlayerx/nn/core/core_torch.py
=> fix parameterlist parameterdict

tensorlayerx/backend/ops/mindspore_nn.py, tensorlayerx/backend/ops/paddle_nn.py, tensorlayerx/backend/ops/tensorflow_nn.py, tensorlayerx/backend/ops/torch_nn.py, tensorlayerx/nn/layers/convolution/depthwise_conv.py, tests/layers/test_layers_convolution.py
=> Update depthwise parameters compatiable with multiple backends

tensorlayerx/backend/ops/paddle_nn.py
=> fix rnn lstm gru weights bug

tensorlayerx/backend/ops/mindspore_backend.py, tensorlayerx/backend/ops/paddle_backend.py, tensorlayerx/backend/ops/tensorflow_backend.py, tensorlayerx/backend/ops/torch_backend.py, tensorlayerx/nn/layers/padding.py, tests/layers/test_layers_padding.py
=> Update padding layers

README.md, setup.py, tensorlayerx/nn/layers/stack.py, tensorlayerx/package_info.py
=> TensorLayerX 0.5.6 release.

tensorlayerx/nn/layers/convolution/mask_conv.py
=> Update mask conv

examples/basic_tutorials/tutorial_tensorlayer_model_load.py, tensorlayerx/nn/core/common.py, tensorlayerx/nn/core/core_mindspore.py, tensorlayerx/nn/core/core_paddle.py, tensorlayerx/nn/core/core_tensorflow.py, tensorlayerx/nn/core/core_torch.py
=> Update TLX training models can be imported into any backend.

examples/basic_tutorials/tutorial_load_paddle_parameters_to_tensorlayerx.py, examples/basic_tutorials/tutorial_load_pytorch_parameters_to_tensorlayerx.py
=> Add the PyTorch and Paddle model parameters to import TensorLayerX

tensorlayerx/model/core.py, tensorlayerx/model/utils.py
=> Fix TrainOneStep

tensorlayerx/model/core.py
=> Fix torch backend acc

tensorlayerx/files/utils.py, tensorlayerx/nn/core/common.py
=> Add parameters save to HDF5

setup.py, tensorlayerx/files/utils.py, tensorlayerx/package_info.py
=> TensorLayerX 0.5.7 release

docs/modules/activation.rst, docs/modules/ops.rst, tensorlayerx/backend/__init__.py, tensorlayerx/backend/ops/__init__.py, tensorlayerx/backend/ops/mindspore_backend.py, tensorlayerx/backend/ops/mindspore_nn.py, tensorlayerx/backend/ops/paddle_backend.py, tensorlayerx/backend/ops/paddle_nn.py, tensorlayerx/backend/ops/tensorflow_backend.py, tensorlayerx/backend/ops/tensorflow_nn.py, tensorlayerx/backend/ops/torch_backend.py, tensorlayerx/backend/ops/torch_nn.py, tensorlayerx/nn/layers/activation.py
=> add topk hardsigmoid, fix split

tensorlayerx/backend/ops/__init__.py, tensorlayerx/backend/ops/mindspore_nn.py, tensorlayerx/backend/ops/paddle_nn.py, tensorlayerx/backend/ops/tensorflow_nn.py, tensorlayerx/backend/ops/torch_nn.py, tensorlayerx/nn/layers/activation.py
=> fix swish and prelu

tensorlayerx/backend/__init__.py, tensorlayerx/backend/ops/__init__.py, tensorlayerx/backend/ops/mindspore_nn.py, tensorlayerx/backend/ops/oneflow_nn.py, tensorlayerx/backend/ops/paddle_nn.py, tensorlayerx/backend/ops/tensorflow_nn.py, tensorlayerx/backend/ops/torch_nn.py, tensorlayerx/losses/mindspore_cost.py, tensorlayerx/losses/oneflow_cost.py, tensorlayerx/losses/paddle_cost.py, tensorlayerx/losses/tensorflow_cost.py, tensorlayerx/losses/torch_cost.py
=> add some functions

tensorlayerx/backend/ops/mindspore_nn.py, tensorlayerx/backend/ops/oneflow_nn.py, tensorlayerx/backend/ops/paddle_nn.py, tensorlayerx/backend/ops/tensorflow_nn.py, tensorlayerx/backend/ops/torch_nn.py, tensorlayerx/nn/layers/pooling.py
=> fix maxpool1d/2d/3d

docs/modules/vision.rst
=> fix docs/vision

tensorlayerx/dataflow/dataloader.py, tensorlayerx/files/dataset_loaders/celebA_dataset.py, tensorlayerx/files/dataset_loaders/cifar10_dataset.py, tensorlayerx/files/dataset_loaders/cyclegan_dataset.py, tensorlayerx/files/dataset_loaders/flickr_1M_dataset.py, tensorlayerx/files/dataset_loaders/flickr_25k_dataset.py, tensorlayerx/files/dataset_loaders/imdb_dataset.py, tensorlayerx/files/dataset_loaders/matt_mahoney_dataset.py, tensorlayerx/files/dataset_loaders/mnist_dataset.py, tensorlayerx/files/dataset_loaders/mnist_fashion_dataset.py, tensorlayerx/files/dataset_loaders/mpii_dataset.py, tensorlayerx/files/dataset_loaders/nietzsche_dataset.py, tensorlayerx/logging/tl_logging.py
=> update files/datasets download info

tensorlayerx/files/dataset_loaders/celebA_dataset.py
=> fix celebA dataset load

tensorlayerx/vision/transforms/utils.py
=> fix load_images

tensorlayerx/nn/layers/convolution/group_conv.py, tensorlayerx/nn/layers/fold.py
fix function '__repr__' in 'tensorlayerx/nn/layers/convolution/group_conv.py'
fix function 'assert_int_or_pair' in 'tensorlayerx/nn/layers/fold.py'
=> fix some bugs

tensorlayerx/backend/ops/mindspore_backend.py, tensorlayerx/backend/ops/mindspore_nn.py, tensorlayerx/backend/ops/paddle_backend.py, tensorlayerx/backend/ops/tensorflow_backend.py
=> fix mindspore backend ops

tensorlayerx/backend/ops/mindspore_backend.py, tensorlayerx/backend/ops/mindspore_nn.py, tensorlayerx/backend/ops/paddle_backend.py, tensorlayerx/backend/ops/tensorflow_backend.py, tensorlayerx/backend/ops/torch_backend.py
=> fix unsorted_segment_ops

.readthedocs.yml, docs/conf.py
=> update readthedocs yml

examples/basic_tutorials/cifar10_cnn_torch_dist.py, examples/basic_tutorials/test_dist.sh, tensorlayerx/backend/ops/__init__.py, tensorlayerx/backend/ops/load_backend.py, tensorlayerx/backend/ops/torch_backend.py, tensorlayerx/distributed/__init__.py, tensorlayerx/distributed/launch.py
support distribution for torch backend
1.add torch distributed init & model function
2.add tlx distributed launch module
3. add torch dist demo & script
=> add torch distribution

tensorlayerx/backend/ops/jittor_backend.py
=> Fix some bugs in jittor backend implement
